# Generated by Django 3.2.7 on 2021-10-26 13:58

import create.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=2000)),
                ('upload_image', models.ImageField(null=True, upload_to=create.models.article_directory_path)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
